{
 "title": "GitOps Platform Lab",
 "tags": [
  "gitops",
  "platform-lab"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Request rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(demo_http_requests_total[1m])) by (path)"
    }
   ]
  },
  {
   "title": "5xx error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(demo_http_requests_total{status=~\"5..\"}[1m]))"
    }
   ]
  },
  {
   "title": "P95 latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(demo_http_request_duration_seconds_bucket[5m])) by (le, path))"
    }
   ]
  },
  {
   "title": "Structured Demo Service logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{namespace=\"platform-lab\", app=\"demo-service\"} | json"
    }
   ]
  }
 ]
}