apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - horizontal-pod-autoscaler.yaml
  - limit-range.yaml
  - network-policy.yaml
  - pod-disruption-budget.yaml
  - resource-quota.yaml

images:
  - name: gitops-platform-lab-demo
    newName: ghcr.io/leonwwest/gitops-platform-lab-demo
    newTag: v0.1.0

patches:
  - path: deployment-patch.yaml
