apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: gitops-platform-lab-demo
    newName: gitops-platform-lab-demo
    newTag: local

patches:
  - path: deployment-patch.yaml
  - path: service-patch.yaml
